name: rest_client
description: RestAPI client package
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  dio: ^5.4.3+1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  very_good_analysis: ^5.1.0
  json_serializable: ^6.8.0
